# Generated by Django 2.0.6 on 2018-08-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180820_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weeks_ripened',
            field=models.DecimalField(decimal_places=0, default=4, max_digits=3),
        ),
    ]
