# Generated by Django 2.0.6 on 2018-08-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_weeks_ripened'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weeks_ripened',
        ),
    ]
