# Generated by Django 2.0.6 on 2018-08-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gender',
            new_name='milk_type',
        ),
    ]
