# Generated by Django 2.0.6 on 2018-08-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180821_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='milk_sanitation',
            field=models.CharField(choices=[['Raw milk', 'none'], ['Thermized', 'thermized'], ['Pasteurized', 'pasteurized']], default='Raw milk', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='milk_type',
            field=models.CharField(choices=[['Cow', 'cow'], ['Goat', 'goat'], ['Sheep', 'sheep']], default='Cow', max_length=12),
        ),
    ]
