# Generated by Django 2.0.6 on 2018-08-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180821_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fat_content',
            field=models.CharField(choices=[['30+', '30+'], ['48+', '48+'], ['50+', '50+']], default='48+', max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='ripening',
            field=models.CharField(choices=[['4-8 weeks', '4-8 weeks'], ['8-12 weeks', '8-12 weeks'], ['2-3 months', '2-3 months'], ['4-7 months', '4-7 months'], ['7-10 months', '7-10 months'], ['10-12 months', '10-12 months'], ['14+ months', '14+ months'], ['2-12 months', '2-12 months'], ['2-14+ months', '2-14+ months']], default='2-14+ months', max_length=16),
        ),
    ]
